version: "3.7"

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000

  accounts:
    build: ./com3014-accounts
    volumes:
      - ./com3014-accounts:/usr/src/app
    ports:
      - 8080:8080
    env_file:
      - ./com3014-accounts/.env
