version: "3.7"

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000

  accounts:
    build: ./com3014-accounts
    volumes:
      - ./com3014-accounts:/usr/src/app
    ports:
      - 8080:8080
    env_file:
      - ./com3014-accounts/.env

  questions:
    build: ./question
    volumes:
      - ./question:/usr/src/app
    ports:
      - 1337:1337

  template_db:
    image: postgres:11.4-alpine
  template_web:
    build: ./quiz-template
    command: bundle exec rails s -p 3002 -b '0.0.0.0'
    volumes:
      - ./quiz-template:/testing_docker
    ports:
      - "3002:3002"
    depends_on:
      - template_db
